"""Rebuild the about page's facility grid from whatever photos exist.

Drop photos in images/facility/ named floor.jpg / operations.jpg / dispatch.jpg
— see images/facility/SHOOT-LIST.md — then run:

    python tools/build-facility-photos.py

With no photos the section renders a single honest tile using the one real
photograph we have, rather than repeating it three times under three different
labels. Idempotent; safe to re-run as photos arrive.
"""
from __future__ import annotations

import io
import os
import re
import sys

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow is required:  pip install Pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "images", "facility")
OUT = os.path.join(ROOT, "images")
PAGE = os.path.join(ROOT, "about.html")

W, H = 1600, 900
QUALITY = 78
EXTS = (".jpg", ".jpeg", ".png", ".webp", ".heic", ".bmp", ".tif", ".tiff")

START = "<!-- facility:start — generated by tools/build-facility-photos.py -->"
END = "<!-- facility:end -->"

# slot -> (label, sprite icon, alt text). Icons must exist in about.html's sprite.
SLOTS = [
    ("floor", "Knitting Floor — 18+ Circular Machines", "factory",
     "DHOWN Hosiery Mills knitting floor with circular knitting machines, Ludhiana"),
    ("operations", "Machine Operations", "gear",
     "Circular knitting machine in operation at DHOWN Hosiery Mills"),
    ("dispatch", "Quality Check &amp; Dispatch", "package",
     "Finished knitted fabric rolls checked and prepared for dispatch"),
]

FALLBACK = ("images/machine.jpg", "Our Knitting Floor — Ludhiana", "factory",
            "DHOWN Hosiery Mills circular knitting machine, Ludhiana")

IMG_STYLE = ("position:absolute;inset:0;width:100%;height:100%;"
             "object-fit:cover;")


def find_raw() -> dict[str, str]:
    found = {}
    if not os.path.isdir(RAW):
        return found
    known = {s[0] for s in SLOTS}
    for fn in sorted(os.listdir(RAW)):
        stem, ext = os.path.splitext(fn)
        if ext.lower() not in EXTS:
            continue
        slot = stem.lower().strip()
        if slot in known:
            found[slot] = os.path.join(RAW, fn)
        else:
            print(f"  ?  {fn}: '{slot}' is not a known slot, skipped")
    return found


def process(src: str, dst: str) -> str:
    im = ImageOps.exif_transpose(Image.open(src)).convert("RGB")
    im = ImageOps.fit(im, (W, H), Image.LANCZOS, centering=(0.5, 0.5))
    im.save(dst, "JPEG", quality=QUALITY, optimize=True, progressive=True)
    return f"{os.path.getsize(dst) / 1024:.0f} KB"


def tile(src: str, label: str, icon: str, alt: str, large: bool) -> str:
    cls = "facility-img facility-img-large" if large else "facility-img"
    return (
        f'      <div class="{cls}" data-reveal>\n'
        f'        <img src="{src}" alt="{alt}" loading="lazy" decoding="async"\n'
        f'             style="{IMG_STYLE}">\n'
        f'        <div class="facility-img-label">'
        f'<svg class="ico" aria-hidden="true"><use href="#i-{icon}"/></svg> {label}</div>\n'
        f'      </div>'
    )


def build(built: list[str]) -> str:
    if not built:
        src, label, icon, alt = FALLBACK
        tiles = [tile(src, label, icon, alt, True)]
    else:
        avail = [s for s in SLOTS if s[0] in built]
        # One photo -> full-width banner. Two -> side by side. Three+ -> banner
        # plus a row beneath, which is what the CSS grid was designed for.
        big = len(avail) != 2
        tiles = [
            tile(f"images/facility-{slot}.jpg", label, icon, alt,
                 large=(i == 0 and big))
            for i, (slot, label, icon, alt) in enumerate(avail)
        ]
    return (f'    {START}\n'
            f'    <div class="facility-grid">\n'
            + "\n".join(tiles)
            + f'\n    </div>\n'
            f'    {END}')


def find_grid(html: str) -> tuple[int, int] | None:
    """Span of the whole <div class="facility-grid"> block, nesting-aware.

    Returns (start, end) offsets covering the opening tag through its matching
    close, with the opening tag's leading indentation included.
    """
    m = re.search(r'[ \t]*<div class="facility-grid">', html)
    if not m:
        return None
    depth = 0
    for tag in re.finditer(r'<div\b|</div>', html[m.start():]):
        depth += 1 if tag.group(0) != "</div>" else -1
        if depth == 0:
            return m.start(), m.start() + tag.end()
    return None


def main() -> int:
    raw = find_raw()
    built = []
    if raw:
        print(f"Processing {len(raw)} facility photo(s) -> {W}x{H}\n")
        for slot, src in raw.items():
            dst = os.path.join(OUT, f"facility-{slot}.jpg")
            try:
                size = process(src, dst)
            except Exception as exc:                  # noqa: BLE001
                print(f"  !  {slot}: {exc}")
                continue
            built.append(slot)
            print(f"  ok {slot:11} {size}")
        print()
    else:
        print("No facility photos yet — rendering the single-tile fallback.\n")

    html = io.open(PAGE, encoding="utf-8").read()
    block = build(built)

    if START in html and END in html:
        html = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block,
                      html, count=1, flags=re.S)
    else:
        # First run: replace the hand-written grid. The grid contains nested
        # divs, so find its real closing tag by depth rather than with a
        # non-greedy regex, which would stop at the first </div> inside it.
        span = find_grid(html)
        if span is None:
            sys.exit("Could not find the facility grid in about.html")
        start, end = span
        html = html[:start] + block + html[end:]

    io.open(PAGE, "w", encoding="utf-8", newline="\n").write(html)

    n = len(built)
    print(f"about.html facility grid rebuilt — "
          f"{n if n else 'no'} real photo(s), "
          f"{'fallback tile' if not n else str(n) + ' tile(s)'}")
    missing = [s[0] for s in SLOTS if s[0] not in built]
    if missing:
        print("Still needed: " + ", ".join(missing))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
